x_range:
  start: 0
  end: 50
  steps: 10

y_range:
  start: 0
  end: 50
  steps: 10

max_retries: 3
rolling_window_size: 6

logging_level: "INFO"
output_csv: "output/scan_data.csv"
heatmap_output: "output/heatmap.png"
